import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import type {
  FullResult,
  Reporter,
  TestCase,
  TestResult,
} from '@playwright/test/reporter';

interface AnalysisRecord {
  test: string;
  url: string;
  error: string;
  analysis: {
    summary: string;
    category: string;
    rootCause: string;
    suggestedFix: string;
  };
}

/**
 * Custom Playwright reporter that collects the `failure-analysis` attachments
 * produced by the v7 fixture and writes a standalone report
 * (playwright-report/failure-analysis.html + .json). This is the "attach the
 * explanation to your test report" half of Task 3 Option A.
 */
export default class FailureAnalysisReporter implements Reporter {
  private readonly records: AnalysisRecord[] = [];

  onTestEnd(_test: TestCase, result: TestResult): void {
    for (const attachment of result.attachments) {
      if (attachment.name !== 'failure-analysis') continue;
      const raw = attachment.body?.toString('utf-8')
        ?? (attachment.path ? readFileSync(attachment.path, 'utf-8') : '');
      try {
        const parsed = JSON.parse(raw) as AnalysisRecord;
        if (parsed.analysis) this.records.push(parsed);
      } catch {
        // Non-JSON attachment (e.g. the "skipped" note) — ignore.
      }
    }
  }

  async onEnd(_result: FullResult): Promise<void> {
    const dir = resolve(process.cwd(), 'playwright-report');
    mkdirSync(dir, { recursive: true });
    writeFileSync(resolve(dir, 'failure-analysis.json'), JSON.stringify(this.records, null, 2));
    writeFileSync(resolve(dir, 'failure-analysis.html'), this.html());
    if (this.records.length > 0) {
      // eslint-disable-next-line no-console
      console.log(`\nFailure analysis: ${this.records.length} explained -> playwright-report/failure-analysis.html`);
    }
  }

  private html(): string {
    const escape = (s: string): string =>
      s.replace(/[&<>]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c] as string));
    const badge = (category: string): string => {
      const color = { 'product-bug': '#c0392b', environment: '#8a5a00', flaky: '#1f6feb', 'test-bug': '#128a54' }[category] ?? '#5a6b80';
      return `<span style="background:${color};color:#fff;border-radius:999px;padding:2px 10px;font-size:12px;font-weight:700">${escape(category)}</span>`;
    };
    const cards = this.records.length === 0
      ? '<p>No failures analyzed in this run.</p>'
      : this.records.map((r) => `
        <article style="border:1px solid #dce3ee;border-radius:12px;padding:18px;margin:14px 0;background:#fff">
          <div style="display:flex;justify-content:space-between;gap:12px;align-items:center">
            <strong>${escape(r.test)}</strong>${badge(r.analysis.category)}
          </div>
          <p style="color:#131b2b">${escape(r.analysis.summary)}</p>
          <p><strong>Root cause:</strong> ${escape(r.analysis.rootCause)}</p>
          <p><strong>Suggested fix:</strong> ${escape(r.analysis.suggestedFix)}</p>
          <details><summary style="cursor:pointer;color:#5a6b80">error &amp; url</summary>
            <pre style="white-space:pre-wrap;background:#0f1729;color:#d7e2f4;border-radius:8px;padding:12px;font-size:12px">${escape(r.url)}\n\n${escape(r.error)}</pre>
          </details>
        </article>`).join('');
    return `<!doctype html><html lang="en"><head><meta charset="utf-8"/>
<title>Failure Analysis</title><meta name="viewport" content="width=device-width, initial-scale=1"/></head>
<body style="font-family:-apple-system,Segoe UI,Roboto,Arial,sans-serif;max-width:900px;margin:0 auto;padding:32px;color:#131b2b">
<h1>Failure Analysis (xAI)</h1>
<p style="color:#5a6b80">Generated by FailureAnalysisReporter. ${this.records.length} failure(s) explained.</p>
${cards}
</body></html>`;
  }
}
